"""Recreate Question table

Revision ID: 939837f57cfb
Revises: a169c0328134
Create Date: 2025-05-27 10:12:52.714677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939837f57cfb'
down_revision = 'a169c0328134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
