"""add checkin and tip tables

Revision ID: a169c0328134
Revises: ca8d5d3d0845
Create Date: 2025-05-27 09:51:05.454262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a169c0328134'
down_revision = 'ca8d5d3d0845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('anxious', sa.Boolean(), nullable=True),
    sa.Column('depressed', sa.Boolean(), nullable=True),
    sa.Column('no_food', sa.Boolean(), nullable=True),
    sa.Column('body_discomfort', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('exercised', sa.Boolean(), nullable=True),
    sa.Column('drank_water', sa.Boolean(), nullable=True),
    sa.Column('skincare', sa.Boolean(), nullable=True),
    sa.Column('went_outside', sa.Boolean(), nullable=True),
    sa.Column('made_bed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tip')
    op.drop_table('check_in')
    # ### end Alembic commands ###
