"""Atualiza modelo CheckIn com campos de hábitos e estado emocional

Revision ID: bcdcb2b75c7a
Revises: 939837f57cfb
Create Date: 2025-05-27 11:46:28.636965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdcb2b75c7a'
down_revision = '939837f57cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=200), nullable=True))
        batch_op.alter_column('mood',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
