"""Added website and email fields to Resource model

Revision ID: ca8d5d3d0845
Revises: 
Create Date: 2025-05-26 11:38:06.244802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8d5d3d0845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=300), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('website')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
